name: Trigger auto deployment for engine

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/engine-AutoDeployTrigger-0aea227f-efd1-4ae2-aa3d-174d09b4645f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ENGINE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ENGINE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ENGINE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/engine
          dockerfilePath: ${{ github.workspace }}/engine/Dockerfile
          registryUrl: rgcompliance1809.azurecr.io
          registryUsername: ${{ secrets.ENGINE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ENGINE_REGISTRY_PASSWORD }}
          containerAppName: engine
          resourceGroup: rg-compliance
          imageToBuild: rgcompliance1809.azurecr.io/engine:${{ github.sha }}
